version: '3.7'

services:

  neo4jtbv:
    image: "neo4j:4.0"
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - neo4jtbvdb:/data
    - neo4jtbvplugins:/plugins
    environment:
    - NEO4J_AUTH=neo4j/PasSW0rd
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*

volumes:
  neo4jtbvdb:
  neo4jtbvplugins:
    driver: local
    driver_opts:
      type: none
      device: $PWD/neo4jplugins
      o: bind
